In [1]:
import numpy as np
import torch
import tensorflow as tf

# **Soal No 1**

In [2]:
# Buat matrix X dengan ukuran 2x3 menggunakan NUMPY
X = np.array([[23, 9, 6], [25, 61, 110]])
X

array([[ 23,   9,   6],
       [ 25,  61, 110]])

In [3]:
# Buat matrix X_pt dengan ukuran 2x3 menggunakan PYTORCH
X_pt = torch.tensor([[6, 9, 23], [110, 61, 25]])
X_pt

tensor([[  6,   9,  23],
        [110,  61,  25]])

In [4]:
# Buat matrix X_tf dengan ukuran 2x3 menggunakan TENSORFLOW
X_tf = tf.Variable([[9, 6, 23], [61, 15, 25]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 9,  6, 23],
       [61, 15, 25]], dtype=int32)>

# **Soal No 2**
Lakukan transpose pada matrix X, X_pt dan X_tf

In [5]:
# Transpose matriks X
X_t = X.T
X_t

array([[ 23,  25],
       [  9,  61],
       [  6, 110]])

In [6]:
# Transpose matriks X_pt
X_pt_t = X_pt.T
X_pt_t

tensor([[  6, 110],
        [  9,  61],
        [ 23,  25]])

In [8]:
X_tf_t =tf.transpose(X_tf)
X_tf_t

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 61],
       [ 6, 15],
       [23, 25]], dtype=int32)>