In [1]:
import numpy as np
import torch
import tensorflow as tf

# **Soal No. 1**

In [2]:
# Buat matrix X dengan ukuran 2x3 menggunakan NUMPY
X = np.array([[23, 9, 6], [25, 15, 11]])
X

array([[23,  9,  6],
       [25, 15, 11]])

In [3]:
# Buat matrix X_pt dengan ukuran 2x3 menggunakan PYTORCH
X_pt = torch.tensor([[2, 3, 9], [2, 5, 6]])
X_pt

tensor([[2, 3, 9],
        [2, 5, 6]])

In [4]:
# Buat matrix X_tf dengan ukuran 2x3 menggunakan TENSORFLOW
X_tf = tf.Variable([[9, 6, 23], [15, 61, 11]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 9,  6, 23],
       [15, 61, 11]], dtype=int32)>

Lakukan perkalian matrix X, X_pt dan X_tf dengan suatu skalar

In [5]:
X*2

array([[46, 18, 12],
       [50, 30, 22]])

In [6]:
X_pt*2

tensor([[ 4,  6, 18],
        [ 4, 10, 12]])

In [7]:
X_tf*2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 18,  12,  46],
       [ 30, 122,  22]], dtype=int32)>

Lakukan penjumlahan matrix X, X_pt dan X_tf dengan suatu skalar

In [8]:
X+3

array([[26, 12,  9],
       [28, 18, 14]])

In [9]:
X_pt+3

tensor([[ 5,  6, 12],
        [ 5,  8,  9]])

In [10]:
X_tf+3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[12,  9, 26],
       [18, 64, 14]], dtype=int32)>

Lakukan pengurangan matrix X, X_pt dan X_tf dengan suatu skalar

In [11]:
X-4

array([[19,  5,  2],
       [21, 11,  7]])

In [12]:
X_pt-4

tensor([[-2, -1,  5],
        [-2,  1,  2]])

In [13]:
X_tf-4

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 5,  2, 19],
       [11, 57,  7]], dtype=int32)>

# **Soal No.2**

In [14]:
# Buat matrix Y dengan ukuran 2x3 menggunakan NUMPY
Y = np.array([[2, 3, 9], [2, 5, 1]])
Y

array([[2, 3, 9],
       [2, 5, 1]])

In [16]:
# Buat matrix Y_pt dengan ukuran 2x3 menggunakan PYTORCH
Y_pt = torch.tensor([[9, 6, 23], [15, 61, 11]])
Y_pt

tensor([[ 9,  6, 23],
        [15, 61, 11]])

In [17]:
# Buat matrix Y_tf dengan ukuran 2x3 menggunakan TENSORFLOW
Y_tf = tf.Variable([[2, 3, 4], (21, 20, 26)])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  3,  4],
       [21, 20, 26]], dtype=int32)>

In [18]:
# Kalikan matrix X dengan Y
X*Y

array([[46, 27, 54],
       [50, 75, 11]])

In [19]:
# Kalikan matrix X_pt tdengan Y_pt
X_pt*Y_pt

tensor([[ 18,  18, 207],
        [ 30, 305,  66]])

In [20]:
# Kalikan matrix X_tf dengan Y_tf
X_tf*Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[  18,   18,   92],
       [ 315, 1220,  286]], dtype=int32)>