In [1]:
import numpy as np
import torch
import tensorflow as tf

# **Soal No 1**

In [10]:
# Buat matrix X dengan ukuran 2x3 menggunakan NUMPY
X = np.array([[25, 15, 110], [61, 23, 9]])
X

array([[ 25,  15, 110],
       [ 61,  23,   9]])

In [11]:
# Hitung beberapa hasil penjumlahan elemen matrix X dengan fungsi sum
X.sum()

np.int64(243)

In [14]:
# Buat matrix X_tf dengan ukuran 2x3 menggunakan TENSORFLOW
X_tf = tf.Variable([[2, 5, 11], [5, 6, 1]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 2,  5, 11],
       [ 5,  6,  1]], dtype=int32)>

# **Soal No 2**

In [9]:
# Hitung hasil PENJUMLAHAN seluruh elemen matrix X
np.sum(X)

np.int64(253)

In [17]:
# Hitung hasil PENJUMLAHAN seluruh elemen matrix X_pt
X_pt = torch.tensor([[20, 6, 23], [25, 61, 11]])
X_pt

tensor([[20,  6, 23],
        [25, 61, 11]])

In [18]:
torch.sum(X_pt)

tensor(146)

In [15]:
# Hitung hasil PENJUMLAHAN seluruh elemen matrix X_tf
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=30>

# **Soal No 3**

In [19]:
# Hitung hasil penjumlahan matrix X berdasarkan ROW nya
X.sum(axis=0)

array([ 86,  38, 119])

In [20]:
# Hitung hasil penjumlahan matrix X_pt berdasarkan ROW nya
torch.sum(X_pt, 0)

tensor([45, 67, 34])

In [21]:
# Hitung hasil penjumlahan matrix X_tf berdasarkan ROW nya
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 11, 12], dtype=int32)>

# **Soal No 4**

In [22]:
# Hitung hasil penjumlahan matrix X berdasarkan KOLOM nya
X.sum(axis=1)

array([150,  93])

In [23]:
# Hitung hasil penjumlahan matrix X_pt berdasarkan KOLOM nya
torch.sum(X_pt, 1)

tensor([49, 97])

In [24]:
# Hitung hasil penjumlahan matrix X_tf berdasarkan KOLOM nya
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([18, 12], dtype=int32)>

# **Soal No 5**

Hitung nilai MINIMAL dari matrix X, X_pt, X_tf

In [26]:
X.min()

np.int64(9)

In [27]:
X_pt.min()

tensor(6)

In [29]:
tf.reduce_min(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

Hitung nilai MAKSIMAL dari matrix X, X_pt, X_tf

In [30]:
X.max()

np.int64(110)

In [31]:
X_pt.max()

tensor(61)

In [32]:
tf.reduce_max(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=11>

Hitung nilai RATA RATA dari matrix X, X_pt, X_tf

In [33]:
X.mean()

np.float64(40.5)

In [36]:
X_pt.float().mean()

tensor(24.3333)

In [37]:
tf.reduce_mean(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

# **Soal No 6**

In [38]:
# Hitung hasil PERKALIAN sleuruh elemen X
X.prod()

np.int64(520863750)

In [39]:
# Hitung hasil PERKALIAN sleuruh elemen X_pt
torch.prod(X_pt)

tensor(46299000)

In [40]:
# Hitung hasil PERKALIAN sleuruh elemen X_tf
tf.reduce_prod(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=3300>