# **Soal No 1**

In [1]:
import numpy as np

In [4]:
# Buat matrix X berukuran 2x3 menggunakan numpy
x = np.array([[23, 9, 6],
              [25, 61, 110]])
x

array([[ 23,   9,   6],
       [ 25,  61, 110]])

In [5]:
# Tampilkan ukuran dari matrix X
x.shape

(2, 3)

In [8]:
# Tampilkan seluruh elemen dari KOLOM PERTAMA dari matrix X
x[:, 0]

array([23, 25])

In [9]:
# Tampilkan seluruh elemen dari BARIS KEDUA dari matrix X
x[1, :]

array([ 25,  61, 110])

# **Soal No 2**

Ulangi soal nomor 1 menggunakan PYTORCH

In [2]:
import torch

In [10]:
# Buat matrix X berukuran 2x3 menggunakan pytorch
x_pt = torch.tensor([[23, 9, 6],
              [25, 61, 110]])
x_pt

tensor([[ 23,   9,   6],
        [ 25,  61, 110]])

In [11]:
# Tampilkan ukuran dari matrix X
x_pt.shape

torch.Size([2, 3])

In [13]:
# Tampilkan seluruh elemen dari KOLOM PERTAMA dari matrix X
x_pt[:, 0]

tensor([23, 25])

In [15]:
# Tampilkan seluruh elemen dari BARIS KEDUA dari matrix X
x_pt[1, :]

tensor([ 25,  61, 110])

Ulangi soal nomor 1 menggunakan TENSORFLOW

In [3]:
import tensorflow as tf

In [19]:
# Buat matrix X berukuran 2x3 menggunakan tensorflow
x_tf = tf.Variable([[23, 9, 6],
              [25, 61, 110]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[ 23,   9,   6],
       [ 25,  61, 110]], dtype=int32)>

In [20]:
# Tampilkan ukuran dari matrix X
x_tf.shape

TensorShape([2, 3])

In [23]:
# Tampilkan seluruh elemen dari KOLOM PERTAMA dari matrix X
x_tf[:, 0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 25], dtype=int32)>

In [24]:
# Tampilkan seluruh elemen dari BARIS KEDUA dari matrix X
x_tf[1, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 25,  61, 110], dtype=int32)>