# **Soal No 1**

In [1]:
import numpy as np

In [3]:
# Buat vector x dengan ukuran 3x1
x = np.array ([[25],
               [15],
               [110]])
x

array([[ 25],
       [ 15],
       [110]])

In [6]:
# Hitung nilai L2 norm dari vector x
norms = np.linalg.norm(x)
norms

np.float64(113.79806676741042)

# **Soal No 2**

In [5]:
# Buat vector v dengan elemen (3,4)
v = np.array ([3, 4])
v

array([3, 4])

In [7]:
# Hitung nilai L2 norm dari vector v
norm = np.linalg.norm(v)
norm

np.float64(5.0)

In [8]:
# Tampilkan unit vector dari vector v
unit_v = v / norm
unit_v

array([0.6, 0.8])

In [9]:
# Hitung panjang unit vector dari vector v
norm_unit_v = np.linalg.norm(unit_v)
norm_unit_v

np.float64(1.0)