# **Soal No 1**

In [1]:
import numpy as np

In [2]:
# Buat vektor x dengan ukuran 3x1
x = np.array([[25],
              [15],
              [110]])
x

array([[ 25],
       [ 15],
       [110]])

In [3]:
# Hitung panjang vektor x
len(x)

3

In [4]:
# Tampilkan ukuran vektor x
x.shape

(3, 1)

In [5]:
# Tampilkan tipe data dari vektor x
type(x)

numpy.ndarray

In [7]:
# Akses elemen pertama dari vektor
x[0]

array([25])

In [8]:
# Tampilkan tipe data elemen pertama vektor x
type(x[0])

numpy.ndarray

# **Soal No 2**

In [9]:
# Lakukan tranpose pada vektor x dan simpan pada variabel x_t
x_t = x.T
x_t

array([[ 25,  15, 110]])

In [10]:
# Tampilkan ukuran dari vektor x_t
x_t.shape

(1, 3)

In [11]:
y = np.array([[25, 61, 110]])
y

array([[ 25,  61, 110]])

In [12]:
# Lakukan transpose pada vector y dan simpan pada variabel y_t
y_t = y.T
y_t

array([[ 25],
       [ 61],
       [110]])

In [13]:
# Tampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

# **Soal No 3**


In [14]:
import torch
import tensorflow as tf

Soal nomor 2 menggunakan PYTORCH

In [15]:
x_pt = torch.tensor([[25],
                     [15],
                     [110]])
x_pt

tensor([[ 25],
        [ 15],
        [110]])

In [16]:
# Lakukan tranpose pada vektor x dan simpan pada variabel x_t
x_pt_t = x_pt.T
x_pt_t

tensor([[ 25,  15, 110]])

In [17]:
# Tampilkan ukuran dari vektor x_t
x_pt.shape

torch.Size([3, 1])

In [19]:
y_pt = torch.tensor([[25, 61, 110]])
y_pt

tensor([[ 25,  61, 110]])

In [20]:
# Lakukan transpose pada vector y dan simpan pada variabel y_t
y_pt_t = y_pt.T
y_pt_t

tensor([[ 25],
        [ 61],
        [110]])

In [21]:
# Tampilkan ukuran dari vector x_t
y_pt.shape

torch.Size([1, 3])

Soal nomor 2 menggunakan TENSORFLOW

In [22]:
x_tf = tf.Variable([[25],
                     [15],
                     [110]])
x_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[ 25],
       [ 15],
       [110]], dtype=int32)>

In [25]:
# Lakukan tranpose pada vektor x dan simpan pada variabel x_t
# Tampilkan ukuran dari vektor x_t
x_tf_t = tf.transpose(x_tf)
x_tf_t

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 25,  15, 110]], dtype=int32)>

In [26]:
y_tf = torch.tensor([[25, 61, 110]])
y_tf

tensor([[ 25,  61, 110]])

In [27]:
# Lakukan transpose pada vector y dan simpan pada variabel y_t
# Tampilkan ukuran dari vector x_t
y_tf_t = tf.transpose(y_tf)
y_tf_t

<tf.Tensor: shape=(3, 1), dtype=int64, numpy=
array([[ 25],
       [ 61],
       [110]])>