# **Soal No 1**
Buatlah matrix ukuran 3x3 lalu hitung nilai Frobenius Norm

NUMPY

In [1]:
import numpy as np

In [3]:
X = np.array([[1, 1, 0], [2, 3, 9], [2, 5, 6]])
X

array([[1, 1, 0],
       [2, 3, 9],
       [2, 5, 6]])

In [4]:
np.linalg.norm(X)

np.float64(12.68857754044952)

PYTORCH

In [5]:
import torch

In [6]:
X_pt = torch.tensor([[11, 61, 15], [23, 9, 6], [21, 4, 26]])
X_pt

tensor([[11, 61, 15],
        [23,  9,  6],
        [21,  4, 26]])

In [14]:
torch.norm(X_pt.float())

tensor(76.4591)

TENSORFLOW

In [9]:
import tensorflow as tf

In [16]:
X_tf = tf.Variable([[18, 30, 1], [3, 34, 28.], [2, 5, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[18., 30.,  1.],
       [ 3., 34., 28.],
       [ 2.,  5.,  7.]], dtype=float32)>

In [17]:
tf.norm(X_tf)

<tf.Tensor: shape=(), dtype=float32, numpy=57.026309967041016>