# **Soal No 1**
Buat Matrix A dengan ukuran 2x3 dan Vector b berukuran 3x1

NUMPY

In [1]:
import numpy as np

In [2]:
A = np.array([[23, 9, 6], [25, 15, 61]])
A

array([[23,  9,  6],
       [25, 15, 61]])

In [13]:
b = np.array([[2], [1], [4]])
b

array([[2],
       [1],
       [4]])

PYTORCH

In [6]:
import torch

In [7]:
A_pt = torch.tensor([[9, 23, 6], [61, 11, 25]])
A_pt

tensor([[ 9, 23,  6],
        [61, 11, 25]])

In [14]:
b_pt = torch.tensor([[3], [5], [1]])
b_pt

tensor([[3],
        [5],
        [1]])

TENSORFLOW

In [11]:
import tensorflow as tf

In [12]:
A_tf = tf.Variable([[2, 3, 9], [6, 1, 1]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 9],
       [6, 1, 1]], dtype=int32)>

In [15]:
b_tf = tf.Variable([[2], [2], [6]])
b_tf

<tf.Variable 'Variable:0' shape=(3, 1) dtype=int32, numpy=
array([[2],
       [2],
       [6]], dtype=int32)>

# **Soal No 2**
Tampilkan ukuran matriks A dan b

In [16]:
A.shape

(2, 3)

In [17]:
b.shape

(3, 1)

# **Soal No 3**

In [19]:
# Kalikan matriks A dengan vector b
np.dot(A, b)

array([[ 79],
       [309]])

In [21]:
# Kalikan matriks A_pt dengan vector b_pt
torch.matmul(A_pt, b_pt)

tensor([[148],
        [263]])

In [23]:
# Kalikan matriks A_tf dengan vector b
tf.matmul(A_tf, b_tf)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[64],
       [20]], dtype=int32)>

# **Soal No 4**
Buat matriks B ukuran 3x3

NUMPY

In [24]:
B = np.array([[23, 9, 6], [21, 4, 26], [25, 62, 110]])
B

array([[ 23,   9,   6],
       [ 21,   4,  26],
       [ 25,  62, 110]])

PYTORCH

In [26]:
B_pt = torch.tensor([[2, 3, 9], [2, 1, 4], [6, 1, 1]])
B_pt

tensor([[2, 3, 9],
        [2, 1, 4],
        [6, 1, 1]])

TENSORFLOW

In [27]:
B_tf = tf.Variable([[9, 6, 23], [4, 4, 27], [15, 61, 11]])
B_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[ 9,  6, 23],
       [ 4,  4, 27],
       [15, 61, 11]], dtype=int32)>

# **Soal No 5**

In [29]:
# Kalikan matriks A dengan matriks B
np.dot(A, B)

array([[ 868,  615, 1032],
       [2415, 4067, 7250]])

In [30]:
# Kalikan matriks A_pt dengan matriks B_pt
torch.matmul(A_pt, B_pt)

tensor([[100,  56, 179],
        [294, 219, 618]])

In [31]:
# Kalikan matriks A_tf dengan matriks B_tf
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[165, 573, 226],
       [ 73, 101, 176]], dtype=int32)>

# **Soal No 6**
Buktikan apakah perkalian matriks berdifat komutatif?

(AB=BA)?

In [32]:
np.dot(A, B)

array([[ 868,  615, 1032],
       [2415, 4067, 7250]])

In [33]:
np.dot(B, A)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Aturan perkalian matriks,

Dua matriks bisa dikalikan jika:

**jumlah KOLOM matriks PERTAMA = jumlah BARIS matriks KEDUA**

**(mxn)(nxp)**

Sedangkan pada soal,

B=(3x3) A=(2x3)

maka (3x3)(2x3)

kolom matriks pertama=3

baris matriks kedua=2

maka tidak bisa dikalikan dan seperti kode diatas akan terjadi error.

**Kesimpulan:**

perkalian matriks **TIDAK bersifat komutatif**.