# **25. Symetric and Identity Matrices**

**Soal No.1**

Buatlah matriks simetris dengan ukuran 3x3 dan buktikan bahwa itu merupakan matriks simetris

In [ ]:
import numpy as np

In [ ]:
X_sym = np.array([[0, 1, 2], [1, 3, 4], [2, 4, 5]])
X_sym

array([[0, 1, 2],
       [1, 3, 4],
       [2, 4, 5]])

In [ ]:
X_sym.T

array([[0, 1, 2],
       [1, 3, 4],
       [2, 4, 5]])

In [10]:
X_sym.T == X_sym

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**Soal No.2**

Menggunakan PYTORCH

In [11]:
import torch

In [13]:
# buatlah matriks identitas I dengan ukuran 4x4
I = torch.tensor([[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
I

tensor([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [14]:
# Buatlah vector b_pt dengan ukuran 4x1
b_pt = torch.tensor ([[25],
                      [15],
                      [61],
                      [110]])
b_pt

tensor([[ 25],
        [ 15],
        [ 61],
        [110]])

In [15]:
# Kalikan matrix I dengan vector b_pt
torch.matmul(I, b_pt)

tensor([[ 25],
        [ 15],
        [ 61],
        [110]])